tasks:
  - name: Run and configure InfluxDB docker image (for development purpose only)
    init: |
      docker run --name influxdb -p 8086:8086 -d influxdb:2.0.7 --reporting-disabled
      docker exec influxdb bash -c "sleep 5s; influx setup -f -u dsmr -p dsmrdsmr -o dsmr -b dsmr -r 0 -t dsmrdsmr"
  
  - name: Install npm dependencies
    init: |
      npm install
      exit
