tasks:
  - name: Run and configure InfluxDB docker image (for development purpose only)
    command: |
      docker run --name influxdb -p 8086:8086 -d influxdb:2.0.7 --reporting-disabled
      echo "If this is a new workspace you need to configure the database. See the README.md for more information"
      
  - name: Install npm dependencies
    init: |
      npm install
      exit
