tasks:
  - name: Run InfluxDB docker image (for development purpose only)
    command: docker run --name influxdb -p 8086:8086 influxdb:2.0.7 --reporting-disabled
    
  - name: Configure InfluxDB when starting a new Gitpod workspace
    init: |
      docker exec -it influxdb /bin/bash
      influx setup -f -u dsmr -p dsmrdsmr -o dsmr -b dsmr -r 0 -t dsmrdsmr

  - name: Install npm dependencies
    init: npm install
