tasks:
  - name: Run and configure InfluxDB docker image (for development purpose only)
    init: docker run --name influxdb -p 8086:8086 influxdb:2.0.7 --reporting-disabled
    command: docker exec -it influxdb /bin/bash \
      influx setup -u dsmr -p dsmrdsmr -o dsmr -b dsmr -r 0 -t dsmrdsmr

  - name: Install npm dependencies
    command: npm install