version: "3.8"

networks:
  dsmr:
    external: false

services:
    influxdb:
        image: influxdb:1.8.6
        container_name: influxdb
        ports:
            - 8086:8086
        networks: [dsmr]

    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - 3000:3000
        networks: [dsmr]
