networks:
  dsmr:
    external: false

services:
    influxdb:
        container_name: influxdb
        build:
          context: .
          dockerfile: Dockerfile-influxdb-dsmr
        ports:
          - 8086:8086
        networks:
          - dsmr
        volumes:
          - ./influx-data:/var/lib/influxdb

    dsmr-client:
        container_name: dsmr-client
        build:
          context: .
          dockerfile: Dockerfile-dsmr-client
        environment:
          - INFLUXDB_HOST=http://influxdb
          - INFLUXDB_PORT=8086
          - TZ=${TZ} # Sets the timezone of the image (see the README.md)
        networks:
          - dsmr
        devices:
          - /dev/ttyUSB0:/dev/ttyUSB0  # Map the host's serial port to the container

    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
          - 3000:3000
        networks:
          - dsmr
        volumes:
          - ./grafana-provisioning:/etc/grafana/provisioning
          - ./dashboards:/var/lib/grafana/dashboards
        environment:
          - GF_AUTH_ANONYMOUS_ENABLED=true
          - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
          - GF_AUTH_ANONYMOUS_HIDE_VERSION=true
          - GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION=true
          - GF_SECURITY_ADMIN_USER=dsmr
          - GF_SECURITY_ADMIN_PASSWORD=dsmr
          - GF_USERS_DEFAULT_THEME=system
          - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/electriciteitsverbruik.json
