networks:
  dsmr:
    external: false

services:
    influxdb:
        image: influxdb-dsmr
        container_name: influxdb
        ports:
          - 8086:8086
        networks:
          - dsmr
        volumes:
          - ./influx-data:/var/lib/influxdb

    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
          - 3000:3000
        networks:
          - dsmr

    dsmr-client:
        image: dsmr-client
        container_name: dsmr-client
        networks:
          - dsmr
