networks:
  dsmr:
    external: false

services:
    influxdb:
        image: influxdb-dsmr
        container_name: influxdb
        ports:
          - 8086:8086
        networks:
          - dsmr
        volumes:
          - ./influx-data:/var/lib/influxdb
        environment:
          - TZ=${TZ}

    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
          - 3000:3000
        networks:
          - dsmr

    dsmr-client:
        image: dsmr-client
        container_name: dsmr-client
        environment:
          - INFLUXDB_HOST=http://influxdb
          - INFLUXDB_PORT=8086
        networks:
          - dsmr
        devices:
          - "/dev/ttyUSB0:/dev/ttyUSB0"  # Mapping host's serial port to the container
