{
 "title": "Electriciteitsverbruik",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "vorigVerbruikHoog", "query": "6643" },
   { "name": "vorigVerbruikLaag", "query": "5392" },
   { "name": "vorigVerbruikTotaal", "query": "2027" }
  ]
 },
 "panels": [
  {
   "title": "Actueel verbruik",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dsmr",
     "query": "SELECT mean(\"power\") FROM \"dsmr\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Verbruik per dag",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "alias": "normaaltarief",
     "groupBy": [
      { "params": [ "1w" ], "type": "time" }
     ],
     "measurement": "dsmr",
     "query": "SELECT last(\"receivedTariff2_max\") - first(\"receivedTariff2_min\") FROM \"dsmr_hourly\" WHERE $timeFilter GROUP BY time(1d, -1h)",
     "select": [
      [
       { "params": [ "receivedTariff1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "daltarief",
     "groupBy": [
      { "params": [ "1w" ], "type": "time" }
     ],
     "measurement": "dsmr",
     "query": "SELECT last(\"receivedTariff1_max\") - first(\"receivedTariff1_min\") FROM \"dsmr_hourly\" WHERE $timeFilter GROUP BY time(1d, -1h)",
     "select": [
      [
       { "params": [ "receivedTariff1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Totaal verbruik",
   "type": "gauge",
   "description": "Huidige verbruik vergeleken met verbruik aan het eind van de vorige factuurperiode ($vorigVerbruikTotaal kW).",
   "gridPos": { "h": 11, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dsmr",
     "query": "SELECT last(\"receivedTariff1\") - $vorigVerbruikLaag + last(\"receivedTariff2\") - $vorigVerbruikHoog FROM \"dsmr\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "receivedTariff1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "receivedTariff2" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Meterstanden",
   "type": "stat",
   "description": "Actuele meterstanden voor dal- en normaaltarief",
   "gridPos": { "h": 11, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "daltarief",
     "measurement": "dsmr",
     "select": [
      [
       { "params": [ "receivedTariff1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "normaaltarief",
     "measurement": "dsmr",
     "select": [
      [
       { "params": [ "receivedTariff2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Verbruik per week",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "alias": "normaaltarief",
     "groupBy": [
      { "params": [ "1w" ], "type": "time" }
     ],
     "measurement": "dsmr",
     "query": "SELECT last(\"receivedTariff2_max\") - first(\"receivedTariff2_min\") FROM \"dsmr_hourly\" WHERE $timeFilter GROUP BY time(1w, -3d1h)",
     "select": [
      [
       { "params": [ "receivedTariff1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "daltarief",
     "groupBy": [
      { "params": [ "1w" ], "type": "time" }
     ],
     "measurement": "dsmr",
     "query": "SELECT last(\"receivedTariff1_max\") - first(\"receivedTariff1_min\") FROM \"dsmr_hourly\" WHERE $timeFilter GROUP BY time(1w, -3d1h)",
     "select": [
      [
       { "params": [ "receivedTariff1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Verbruik per minuut",
   "type": "timeseries",
   "description": "Gemiddeld verbruik (kW) per minuut uitgezet in de tijd",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "verbruik",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dsmr",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}